### ISSUE TITLE
CLI : Command line flags are incorrectly interpreted as values

### ISSUE THREAD

**Issue by jf-virtru** [opentdf/otdfctl#109]
Take the following command, for example:  policy namespaces -name test.com.   This results in the namespace "ame" (-n=ame).  The parser "should" be able to detect that -n or --name flag is not being used and throw a syntax error message.  This same situation applies to other flags too.  

There is an open issue (with pflag) that is related and also presents an alternative action to take:

https://github.com/spf13/pflag/issues/314

**Comment by jakedoublev** [comment]
Thanks for opening this issue! While perhaps unintuitive, this is the current expected behavior with [Pflag](https://github.com/spf13/pflag) driving flag interpretation in the CLI within Cobra. If it is to be fixed, it should be fixed upstream.
