### ISSUE TITLE
CLI should have clean and separate concerns for global flags, config flags, and commands that are not relevant to global flags

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/otdfctl#111]
At present, the following global flags are available for every command:
```bash
Global Flags:
      --config-file string   config file (default is $HOME/.otdfctl.yaml)
      --host string          host:port of the Virtru Data Security Platform gRPC server (default "localhost:8080")
      --json                 output single command in JSON (overrides configured output format)
      --log-level string     log level (debug, info, warn, error, fatal, panic) (default "info")
```

The `host` and `log-level` can be moved to the config file and `config` CLI commands, and the `json` flag is not relevant to several commands. We should also ensure their values are read.

We should employ a helper function and the [pflags MarkHidden](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L441) functionality to hide the global flags not relevant to a given set of subcommands so a user is not confused.

**Comment by jrschumacher** [comment]
Closing in favor of #171
