### ISSUE TITLE
Bug: CLI Attribute name assigned to "CODEOWNERS" when attempting to create with an invalid value

### ISSUE THREAD

**Issue by jf-virtru** [opentdf/otdfctl#114]
Attribute name assigned to "CODEOWNERS" when attempting to create with an invalid value.  

policy attributes create -n *** -s e0c8679b-584a-4866-baaa-275e0d049cbb -r HIERARCHY 
2024/04/12 12:00:25 INFO no client credentials provided. GRPC requests to KAS and services will not be authenticated.
{
  "id": "8e7ec2cb-0ab6-41b0-b542-12194c7b9d6d",
  "namespace": {
    "id": "e0c8679b-584a-4866-baaa-275e0d049cbb",
    "name": "airports.com"
  },
  "name": "CODEOWNERS",
  "rule": 3,
  "values": [
    {}
  ],
  "fqn": "https://airports.com/attr/CODEOWNERS",
  "active": {
    "value": true
  },
  "metadata": {}
}

**Comment by jakedoublev** [comment]
@jf-virtru Is this still a known issue?

**Comment by jakedoublev** [comment]
This is reproducible. 
![Screenshot 2024-06-11 at 1 27 03 PM](https://github.com/opentdf/otdfctl/assets/83739412/01500e39-50b8-4db1-81cb-d364e276274c)

**Comment by jakedoublev** [comment]
Closing as this is an issue in Pflag which our CLI's Cobra framework relies upon. Issue opened in that repo: https://github.com/spf13/pflag/issues/406
