### ISSUE TITLE
CLI Need to standardize error message format

### ISSUE THREAD

**Issue by jf-virtru** [opentdf/otdfctl#116]
Need to standardize error message format.  For some errors we display prominently using a red message box while on others we don't.  The red message box should probably be the standard as it makes the error message much easier to find and identify.  

![image](https://github.com/opentdf/otdfctl/assets/148824550/42aebc26-f26d-4e1c-8187-da19e80ed49f)

![image](https://github.com/opentdf/otdfctl/assets/148824550/9dfd246f-fc94-4166-bf4b-5de8b7e9cff5)

**Comment by jrschumacher** [comment]
@jf-virtru we're going to close this and reassess with our new CLI experience
