### ISSUE TITLE
whether otdfctl has an interface(UI) showing on this port on loopback 

### ISSUE THREAD

**Issue by Rajan251** [opentdf/otdfctl#123]
Built in 3 ms
Watching for config changes in /home/open/otdfctl/go.mod
Environment: "development"
Serving pages from memory
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)

**Comment by jrschumacher** [comment]
Hi @Rajan251 no we don't have a UI, but we do utilize https://github.com/gohugoio/hugo to build the manual documentation. What did you execute that caused this message to display? I need to clean that up since building the documentation will be automated.

**Comment by jrschumacher** [comment]
This was resolved with #149
