### ISSUE TITLE
Selectors: should consume platform flattening functions instead of jq expression syntax

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/otdfctl#125]
### Background
As a result of the [accepted ADR to employ flattening of an Entity Representation into known fields and values](https://github.com/opentdf/platform/issues/610), otdfctl needs to consume the [flattening functions](https://github.com/opentdf/platform/blob/main/lib/flattening/flatten.go) instead of jq syntax when helping admins generate selectors for entitlement.

### Acceptance Criteria

1. any jq evaluation is removed, and any docs are updated
2. flattening functions are employed in their place to provide context to the entitlement of a subject

**Comment by jakedoublev** [comment]
Blocked by https://github.com/opentdf/platform/issues/644

**Comment by jakedoublev** [comment]
This is unblocked and can be prioritized appropriately.

**Comment by jrschumacher** [comment]
Underlying architecture has changed and we are going in a different direction.
