### ISSUE TITLE
Enhancement: CLI config should support profiles

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/otdfctl#171]
Should resolve https://github.com/opentdf/otdfctl/issues/111 & https://github.com/opentdf/otdfctl/issues/166

Other CLI tools utilize a config file with separate profiles, and we could employ a similar approach.

- Viper could be bound to flags and the env
- a CLI command could be employed to switch profiles
- cached auth credentials on the OS could be tied to separate profiles
- variables like `host` which is a required permanent flag and `OTDFCTL_TOKEN_URL` which is read from the environment can be unified

**Comment by jrschumacher** [comment]
Related to #150
