### ISSUE TITLE
get namespace requires flag but isn't clear which flag

### ISSUE THREAD

**Issue by strantalis** [opentdf/otdfctl#195]
When running `otdfctl --host https://$PLATFORM_HOST  policy attributes namespaces get` without the proper flag the only error message displayed is `   ERROR    Flag id is required` but doesn't say which flag is required. 

Also when running `--help`  on this command there is the `id` flag but it doesn't mention that its required. 

```
Flags:
  -h, --help        help for get
  -i, --id string   ID of the attribute namespace
```

**Comment by jakedoublev** [comment]
Id is specified in help output as the required flag
