### ISSUE TITLE
uuid cutoff in table output

### ISSUE THREAD

**Issue by strantalis** [opentdf/otdfctl#199]
When listing attributes the uuid seems to be cutoff. 

![image](https://github.com/opentdf/otdfctl/assets/18211470/6e822ef3-350a-49a9-bf4c-83cdcbe0f773)

Workaround for now is to pass `--json` flag.

**Comment by jakedoublev** [comment]
related/duplicated of https://github.com/opentdf/otdfctl/issues/188

**Comment by jakedoublev** [comment]
Closed by #200
