### ISSUE TITLE
CI: Add opentdf/tests xtest step

### ISSUE THREAD

**Issue by dmihalcik-virtru** [opentdf/otdfctl#347]
The xtest project originally validated that files created in one version of a client library are able to be read by the others. For the go client, it uses the otdfctl tool. 

Over time it has also grown to rely on other features of the otdfctl tool for policy and kas grant management. Adding a call to this will help prevent breakages of the xtest infrastructure and should increase overall velocity as the number of supported clients increases.

**Comment by jakedoublev** [comment]
Agreed. The e2e tests in `otdfctl` should be a reusable workflow that:
1. accepts `workflow_call` as a trigger
2. accepts the platform commit sha when checking out the platform
3. accepts the otdfctl commit sha when checking out otdfctl

This way, the platform CI can test a platform PR branch against otdfctl main, and otdfctl CI can test an otdfctl branch against the platform main.
