### ISSUE TITLE
Namespace grants should listed as a single entry and not the entire tree under the namespace 

### ISSUE THREAD

**Issue by jp-ayyappan** [opentdf/otdfctl#392]
Currently the response to the `list` command results in large number of lines if there is a namespace mapping.

Since the mapping is to a specific namespace; the list command should only give me the single ID that was associated with the KAS.

**Comment by jakedoublev** [comment]
<img width="1295" alt="Screenshot 2024-09-19 at 7 26 54 AM" src="https://github.com/user-attachments/assets/b756af36-bfba-4e29-828c-4dec0d1977a1">
It looks like there is an FQN issue, but how can we reproduce what you saw @jp-ayyappan?

**Comment by jakedoublev** [comment]
Update: I no longer believe there is an issue with the FQN not being provided in response. I had manually updated my database to add that namespace ^ and had not reindexed FQNs. If I'd gone through the service code and called the `CreateNamespace` policy RPC it would have propagated as expected.

**Comment by jakedoublev** [comment]
This should be resolved when the platform release of `service` https://github.com/opentdf/platform/pull/1470 goes out.

**Comment by jakedoublev** [comment]
This should be resolved when the platform release of `service` https://github.com/opentdf/platform/pull/1470 goes out.
