### ISSUE TITLE
ADR: Add automation solution for dependency bumps

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/otdfctl#46]
### Background 

[Dependabot](https://github.com/dependabot/dependabot-core) can bump dependencies as newer versions become available and is installed within the `opentdf` GitHub org. 

### Knowns / Assumptions

1. Automating dependency bumps is a standard practice that saves time and effort.
2. Out of date dependencies are a significant risk to software security.
3. Manual review of dependency bumps almost never entails exploration of the code changed in each commit of a bumped package, and is more likely (in practice) to involve a review of a changelog or even just blind acceptance of a bump given a minor/patch semver.
4. 3rd party dependencies are always risky, and the greatest evaluation occurs when first introducing them. 
5. We have scanning tools in place in the CI pipeline to check vulnerabilities in dependencies.
6. Releases will always involve a QA effort before being published.

Given 2, 3, 4, and 5, it is likely a greater security risk to fall behind in manually approving dependency bumps than to automate their approval and risk a backdoor. 

Whatever is employed for `otdfctl` can be employed across the `opentdf` GitHub org repositories.

### Current state

Dependabot PRs for minor and patch semver bumps are now being set [via GitHub Action](https://github.com/opentdf/otdfctl/blob/main/.github/workflows/dependabot-approve-and-merge.yaml) to auto-merge (squash) and automatically approved in [otdfctl](https://github.com/opentdf/otdfctl/pull/97). However, there is a conflict with CODEOWNERS. A [github bot cannot be added to codeowners](https://github.com/orgs/community/discussions/23064) so at this time a manual approval is still required to merge. There are some potential workarounds:

### Chosen Option

Stick with dependabot and manual approvals. Reassess as needed.

### Options

1. Remove codeownership from go.mod and go.sum
    🟥 easier for malicious actor to sneak a backdoor into a dependency and merge it in
    🟩 faster path forward to automated minor/patch bump approvals
2. Add a "bot" GitHub user to the opentdf org for bot-related activities
    🟩 could use a scoped token (probably a PAT) as a secret in workflows (like PR approval of dependabot PRs) to add a layer of authorization security
    🟩 could add the bot user to CODEOWNERS give it access to the dependency lockfiles, a second layer of authorization
    🟥 more secrets to maintain and keep secure

At this time, we will proceed with manual approval of dependency bump PRs until it becomes a burden sufficient enough to justify a decision on the above or another path forward.

**Comment by jakedoublev** [comment]
Repo permissions update [to allow auto-merge of dependabot PRs](https://github.com/virtru-corp/terraform/pull/4897) is blocked by https://github.com/virtru-corp/terraform/pull/4892

**Comment by jakedoublev** [comment]
Dependabot PRs for `minor` and `patch` semver bumps are now being set to auto-merge (squash) and automatically approved, but there is a conflict with CODEOWNERS. A [github bot cannot be added to codeowners](https://github.com/orgs/community/discussions/23064) so at this time a manual approval is still required to merge. There are some potential workarounds:

1. Remove codeownership from `go.mod` and `go.sum`
    🟥 easier for malicious actor to sneak a backdoor into a dependency and merge it in
    🟩 faster path forward to automated minor/patch bump approvals
2. Add a "bot" GitHub user to the opentdf org for bot-related activities
    🟩 could use a scoped token (probably a PAT) as a secret in workflows (like PR approval of dependabot PRs) to add a layer of authorization security
    🟩 could add the bot user to CODEOWNERS give it access to the dependency lockfiles, a second layer of authorization
    🟥 more secrets to maintain and keep secure

At this time, we will proceed with manual approval of dependency bump PRs until it becomes a burden sufficient enough to justify a discussion around the above.

**Comment by jrschumacher** [comment]
Are automatic bumps limited to minor and patch versions? Or is this done via dependabot?

**Comment by jakedoublev** [comment]
> Are automatic bumps limited to minor and patch versions? Or is this done via dependabot?

Dependabot is [capable of any level of dependency update, and allowing/ignoring specific SemVers](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore). It is [configured in otdfctl](https://github.com/opentdf/otdfctl/blob/main/.github/dependabot.yml#L20) to ignore the platform and SDK dependencies, and [configured in the platform](https://github.com/opentdf/platform/blob/main/.github/dependabot.yml) to open PRs for any kind of dependency update. Once PRs are opened, the CI pipeline is triggered, and branch protections are employed in each repo to required [passing status checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging) before the PRs are mergeable.

From there, we employ the approach suggested by the [GitHub documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request) for dependabot in otdfctl, which is to use a GitHub action ([see otdfctl workflow here](https://github.com/opentdf/otdfctl/blob/main/.github/workflows/dependabot-approve-and-merge.yaml#L29)) to set the PRs to auto-merge, and to be approved if they are SemVer minor/patch bumps. We've scoped those approvals to recognized minor and patch versions, as major versions are always going to have a higher likelihood of causing regressions. Major versions will not be approved, but will still be set to auto-merge (as of today). 

However, the workflow's PR approval of dependabot PRs for minor/patch bumps is currently offering no value because the bot does not meet CODEOWNER requirements over `go.sum` or `go.mod`, meaning a manual approval is still needed. In an eventual state where automated bot-triggered merges are enabled, I would encourage us to continue to scope that automation to known minor and patch bumps only.
