### ISSUE TITLE
Implement a CLI manual solution that minimizes doc drift

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/otdfctl#69]
# Implement a CLI manual solution that minimizes doc drift

## Context and Problem Statement

The Cobra library works really well for generating a manual in the CLI, but this is not the only place our customers will be ingesting the manual. We need a way to generate documentation that can be rendered as HTML, PDF, and the like. 

## Decision Drivers

* Reduce or eliminate documentation drift
* Support i18n
* Enable non-developers to contribute
* Build an HTML based manual

## Considered Options

* Hand-crafted documentation
* Cobra based [solution](https://github.com/spf13/cobra/blob/main/doc/md_docs.go)
* Doc driven CLI + Hugo

## Decision Outcome

Chosen option: Doc driven CLI + Hugo

This approach offers more value to customers with the tradeoff of some DX pain. The assumption is that new CLI commands will be on the rare side as we continue developing the product and the energy will be invested in a TUI or Web experience.

### Hand-crafted documentation

* 🟢 Control over the documentation
* 🟢 Easy to implement 
* 🔴 Prone to documentation drift
* 🔴 High level of collaboration required

### Cobra based solution

This solution will utilize Cobra's pre-build documentation solution.

* 🟢 Code driven documentation
* 🟢 Reduced documentation drift
* 🟡 Additional tool needed for i18n
* 🔴 Little control over the documentation look and feel without enhancements

### Doc driven CLI + Hugo

This approach will utilize markdown files to define the documentation and thus the behavior of the CLI. This will reduce the documentation drift and enable i18n if it becomes needed. The documentation is driven by Hugo's [content management](https://gohugo.io/content-management/).

* 🟢 Markdown based solution
* 🟢 Centralize behavior
* 🟢 Full control over HTML documentation
* 🟡 Small negative impact on DX
  * Feels a little unnatural, but so does i18n with token files
  * Less DRY
  * Slightly slower when running hot (no build first)
* 🟡 Embedded HTML theme via submodule or committed to repo via [Hugo](https://gohugo.io/templates/introduction/)
* 🔴 Bespoke

**Comment by suchak1** [comment]
I don't understand how Hugo would avoid doc drift. Do you have an example or reference?

**Comment by jrschumacher** [comment]
@suchak1 Hugo enables us to build easily consumed documentation as HTML. The markdown is organized as markdown files and then pulled into the code like so...

![CleanShot 2024-04-09 at 10 20 16](https://github.com/opentdf/otdfctl/assets/46549/ee771d2d-904b-4551-9a3b-937afe325b64)

![CleanShot 2024-04-09 at 10 20 57](https://github.com/opentdf/otdfctl/assets/46549/77f5f790-3717-413c-8b4e-2b150e9b8543)

This allows us to expand like this
![CleanShot 2024-04-09 at 10 21 38](https://github.com/opentdf/otdfctl/assets/46549/bc04053e-8a39-49db-a8f2-a01255218f5a)

**Comment by jakedoublev** [comment]
If we go with hand-crated or cobra-based, there is a higher barrier to entry for less technical folks (product/technical writers) to engage with the documentation. Given that, it seems likely we'd build a separate source of truth for technical docs, which would lead to greater potential for doc drift. Option 3 (hugo), gives us one documentation source of truth:
1. for less technical folks to contribute to docs (including styling)
2. for code to consume
3. for internationalization support (with minimal to no engineering engagement necessary)
4. to build a static docs site with

I think option 3's benefits outweigh the costs to DX, which are relatively minimal overall. The only thing worse than no documentation is incorrect documentation, and this seems like the best long-term solution to keep docs in sync.
