### ISSUE TITLE
First iteration of an e2e test

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/otdfctl#81]
Goal is to implement e2e tests for the CLI and the OpenTDF platform using the CLI

## Depends on

- #33 
- (optional) #73 
- (optional) opentdf/platform#355

## Acceptance Criteria

- implement policy
  - CRUD attributes
  - CRUD attribute values
  - CRUD attribute namespaces
- identify painpoints and doc drift (add as comment to this issue)

**Comment by jf-virtru** [comment]
Have covered CRUD for:
policy
  attributes
  kas-registry
  namespaces
  resource-mappings

Issues opened:
https://github.com/opentdf/platform/issues/560
https://github.com/opentdf/otdfctl/issues/107
https://github.com/opentdf/otdfctl/issues/109
https://github.com/opentdf/otdfctl/issues/108

To Be Done
  subject-conditions-sets - have already done prior to change to otdfctl, but need to do again)
  subject-mappings - have already done prior to change to otdfctl, but need to do again
  completion - have generated the script for each env, but not yet implemented 

Not ready for testing
Auth
Interactive
Dev

**Comment by jrschumacher** [comment]
This work was done and we will open another ticket to capture more work towards our e2e story.
