### ISSUE TITLE
Improve the build and deployment process

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/otdfctl#83]
Deployment of releases has some rough edges.

### Signing binaries

Binaries built with Go cannot be executed easily across Apple environments due to the lack of signatures. We need to set up signing certs to ensure our releases are executable.

https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/

Ref: https://github.com/gohugoio/hugo/releases/tag/v0.124.1

### Compressing

Some environments have issues with downloading executables. By compressing them, they can be downloaded. Compression formats should be familiar to the platform.

- windows: zip
- macos: tar.gz
- linux: tar.gz

### Calculate checksums

Example:

```
cat tructl-0.2.0-darwin-arm64 | gzip -1fc | tail -c8 | od -t x4 -N 4 -A n | xargs
```

## Acceptance Criteria

- sign binaries for required platforms
- compress the binaries so that they can be downloaded on any platform
- calculate checksums
- test the binary by downloading

**Comment by pnancarrow** [comment]
Adding a note from some back and forth @jakedoublev and I had about newly discovered requirements. As of June 1, 2023 CAs must ensure that private keys are generated, stored, and used in hardware cryptographic modules.

https://cabforum.org/uploads/Baseline-Requirements-for-the-Issuance-and-Management-of-Code-Signing.v3.7.pdf
